# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('step', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link_user_league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.League')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link_user_league_cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('id_cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cyclist')),
                ('id_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.League')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List_cyclist_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cyclist')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('id_cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cyclist')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.League')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='id_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Stage'),
        ),
        migrations.AddField(
            model_name='list_cyclist_tour',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Tour'),
        ),
        migrations.AddField(
            model_name='league',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Tour'),
        ),
        migrations.AddField(
            model_name='bet',
            name='id_cyclist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Cyclist'),
        ),
        migrations.AddField(
            model_name='bet',
            name='id_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.League'),
        ),
        migrations.AddField(
            model_name='bet',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Tour'),
        ),
        migrations.AddField(
            model_name='bet',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
