# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170729_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclist',
            name='salary',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='link_user_league',
            name='money',
            field=models.IntegerField(default=3000000),
        ),
    ]
