# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_bet_id_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_user_league',
            name='money',
            field=models.IntegerField(default=30000000),
        ),
    ]
