# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170801_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='id_stage',
        ),
        migrations.AddField(
            model_name='result',
            name='id_tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Tour'),
            preserve_default=False,
        ),
    ]
