# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_league_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='details',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='reference',
            field=models.CharField(default='I366IB5FIUBCP2J', max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
