# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170809_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='league',
            name='reference',
            field=models.CharField(default='F74HX20R216T6U2', max_length=20),
        ),
        migrations.AlterField(
            model_name='link_user_league',
            name='creation_date',
            field=models.IntegerField(default=0),
        ),
    ]
